
title: Unix Systems Engineer
email: jack.sims@abyssal-deep.com
description: >- # this means to ignore newlines until "baseurl:"
  -- Filler Description Here -- 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://abyssal-deep.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jackpots28
instagram_username: xblackjack28x
domain: abyssal-deep.com

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
