title: Abyssal-Deep
email: jack.sims@abyssal-deep.com
description: >- # this means to ignore newlines until "baseurl:"
  -- Filler Description Here -- 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://abyssal-deep.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jackpots28
instagram_username: xblackjack28x
domain: abyssal-deep.com


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - about.md
 
social_links:
 - { platform: github,         user_url: "https://github.com/jackpots28" }
 - { platform: instagram,      user_url: "https://www.instagram.com/xblackjack28x" }
 
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
