title: A Personal Blog
author:
  name: Jack Sims
  email: jack.sims@abyssal-deep.com
description: >- # this means to ignore newlines until "baseurl:"
 "A personal [systemd-journald.service] - Not purely inclusive to CompSci Topics"
baseurl: "/" 
url: "https://abyssal-deep.com" # the base hostname & protocol for site

#github_username:  jackpots28
#instagram_username: xblackjack28x
domain: abyssal-deep.com

header_pages:
 # - index.md
 - about.md
 - resume.md
 - references.md

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/jackpots28" }
    - { platform: instagram,      user_url: "https://www.instagram.com/xblackjack28x" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jack-john-sims" }
 
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
